source 'https://rubygems.org'

gem 'fluent-plugin-elasticsearch' , '1.7.0'
gem 'fluent-plugin-parser' , '0.6.1'
gem 'fluent-plugin-concat' , '2.0.0'
gem 'fluent-plugin-record-reformer' , '0.8.2'
gem 'fluent-plugin-better-timestamp' , '0.1.0'
gem 'fluent-plugin-color-stripper' , '0.0.3'
